#!/usr/bin/env python3
##############################################################################%
import datetime


def log_entry(log_file, message):
    with open(log_file, 'a') as f:
        f.write(message)

datetimestamp = datetime.datetime.now().strftime("%Y%m%d")

current_log = f'log/{datetimestamp}.log'

log_entry(current_log, "This is a test message\n")
